# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [ubuntu-22.04, windows-2022]

    runs-on: ${{ matrix.os }}
    env:
      PUBLISH_SUFFIX: snapshots
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      PATCH_NUMBER: ${{ github.event.inputs.patch }}
      PUBLISHING: ${{ github.event.inputs.publish }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: extract version
        id: getversion
        run: echo "::set-output name=version::$(.github/scripts/extract_version.sh"

      - name: build
        env:
          VERSION_NAME: ${{ steps.getversion.outputs.version }}
        run: ./gradlew clean build

      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/

      - name: publish to Modrinth and CurseForge
        env:
          VERSION_NAME: ${{ steps.getversion.outputs.version }}
        if: ${{ runner.os == 'Linux' && matrix.java == '17' && github.event.inputs.publish }} # only publish from one OS with latest Java
        run: ./gradlew publishMod

      - name: Create GitHub Release
        if: ${{ runner.os == 'Linux' && matrix.java == '17' && github.event.inputs.publish }} # only publish from one OS with latest Java
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PUBLISH_GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.getversion.outputs.version }}
          prerelease: false
          files: |
            LICENSE
            build/libs/*.jar
